In [128]:
import pandas as pd
import numpy as np

In [129]:
frame = []
with open('sample.txt') as f:
    line = f.readlines()
    for l in line:
        if l[0] == '#':
            continue
        else:
            frame.append(list(map(float, (l.rstrip('\n').split('\t')[1:]))))

In [130]:
index, columns, value = zip(*frame)

In [131]:
# df = pd.DataFrame(index=range(4,201), columns=range(5,int(max(columns))+1))
df = pd.DataFrame(index=list(map(str, range(1, 513))), columns=list(map(str, range(1,513))))

In [132]:
for i, c, v in zip(index, columns, value):
    idx, col = str(int(i)), str(int(c))
    df[col][idx] = v
df

,1,2,3,4,5,6,7,8,9,10,...,503,504,505,506,507,508,509,510,511,512
1,NaN,NaN,NaN,NaN,0.0,0.000066,0.0,0.0,0.0,0.000061,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000167,0.000397,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.000088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000075,0.000328,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000014
509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
df = df.fillna(0)

In [144]:
npary = df.to_numpy()
npary.shape

(512, 512)

In [147]:
cnt = 10
seq_array = []
target_array = []
for i in range(cnt):
    x = i+1
    seq_path = f"../data/p-make/index/idx{x}.csv"
    target_path = f"../data/p-make/basepairprob/bpp{x}.csv"
    seq_array.append(np.loadtxt(seq_path, delimiter=",", dtype=str))
    target_array.append(np.loadtxt(target_path, delimiter=",", dtype=float))

In [150]:
np.array(target_array).shape

(10, 512, 512)

In [ ]:
pickle.dump(np.stack(target_array), open(f"maxspan100/target_{sys.argv[2]}.pkl", "wb"))